export const technologies = {
  vue: { url: "https://vuejs.org", color: "#42b883" },
  react: { url: "https://reactjs.org", color: "#61dafb" },
  next: { url: "https://nextjs.org", color: "#000000" },
  nuxt: { url: "https://nuxtjs.org", color: "#00c58e" },
  typescript: { url: "https://www.typescriptlang.org", color: "#3178c6" },
  scss: { url: "https://sass-lang.com", color: "#cc6699" },
  expo: { url: "https://expo.dev", color: "#000020" },
  react_native: { url: "https://reactnative.dev", color: "#61dafb" },
  figma: { url: "https://www.figma.com", color: "#f24e1e" },
  arduino: { url: "https://www.arduino.cc", color: "#00979d" },
  node: { url: "https://nodejs.org", color: "#339933" },
  deno: { url: "https://deno.land", color: "#000000" },
  decap: { url: "https://decap.dev", color: "#ff0080" },
  mailgun_api: { url: "https://www.mailgun.com", color: "#3c3c3d" },
  openai_api: { url: "https://www.openai.com", color: "#412991" },
  openweather_api: { url: "https://openweathermap.org", color: "#f17e23" },
  plausible_api: { url: "https://plausible.io", color: "#4a4a55" },
  cloudconvert_api: { url: "https://cloudconvert.com", color: "#ff2d20" },
  formspree_api: { url: "https://formspree.io", color: "#f66a0a" },
  unity: { url: "https://unity.com", color: "#000000" },
  deno_deploy: { url: "https://deno.com/deploy", color: "#000000" },
  supabase: { url: "https://supabase.io", color: "#3fcf8e" },
  vercel: { url: "https://vercel.com", color: "#000000" },
  netlify: { url: "https://www.netlify.com", color: "#00ad9f" },
}